<?
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    $toc = $this->driver->getTOC();
?>
<? if (!empty($toc)): ?>
  <? $tocArray = explode("--", $toc[0]) ?>
  <strong><?=$this->transEsc('Table of Contents')?>: </strong>
  <ul class="toc">
    <? foreach ($tocArray as $splited): ?>
      <? foreach (explode(';', $splited) as $line): ?>
        <li><?=$this->escapeHtml($line)?></li>
      <? endforeach; ?>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <?=$this->transEsc("Table of Contents unavailable")?>.
<? endif; ?>