<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out History'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('Checked Out') . '</em>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h3><?=$this->transEsc('Your Checked Out History')?></h3>
  <?=$this->flashmessages()?>

  <? if (!empty($this->transactions)): ?>

    <ul class="recordSet">
    <? $i = 0; foreach ($this->transactions as $resource): ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <li class="result<?=(++$i % 2 == 0) ? ' alt' : ''?>">
        <div id="record<?=$this->escapeHtml($resource->getUniqueId())?>">
          <div class="span-2">
            <? if ($summThumb = $this->record($resource)->getThumbnail()): ?>
              <img src="<?=$this->escapeHtml($summThumb)?>" class="summcover" alt="<?=$this->transEsc('Cover Image')?>"/>
            <? else: ?>
              <img src="<?=$this->url('cover-unavailable')?>" class="summcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
            <? endif; ?>
          </div>
          <div class="span-10">
            <?
                // If this is a non-missing Solr record, we should display a link:
                if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    echo '<a href="' . $this->recordLink()->getUrl($resource) .
                        '" class="title">' . $title . '</a>';
                } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    echo $this->escapeHtml($ilsDetails['title']);
                } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                }
            ?><br/>
            <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
            <? endif; ?>
            <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
              <?=$this->record($resource)->getFormatList()?>
              <br/>
            <? endif; ?>
            <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['duedate'])): ?>
              <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
              <br />
            <? endif; ?>
			<? if (isset($ilsDetails['returned'])): ?>
              <strong><?=$this->transEsc('Returned')?>: <?=$this->escapeHtml($ilsDetails['returned'])?></strong>
            <? endif; ?>
          </div>
          <div class="clear"></div>
        </div>
      </li>
    <? endforeach; ?>
    </ul>
    <? if ($this->renewForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>

<div class="clear"></div>